name: DeepPepServer
channels:
  - defaults
dependencies:
  - python=3.7.9
  - pip=21.0.1
  - scikit-learn=0.23.2
  - tensorflow=2.3.0
  - pip:
    - fastapi==0.63.0
    - gunicorn==20.1.0
    - h11==0.12.0
    - httptools==0.1.1
    - pydantic==1.7.3
    - python-dotenv==0.15.0
    - pyyaml==5.4.1
    - starlette==0.13.6
    - uvicorn==0.13.4
    - uvloop==0.15.2
    - watchgod==0.7
    - websockets==8.1
