version: "3.9"

services:

  app:
    build: ../
    env_file: .env
    deploy:
      restart_policy:
        max_attempts: 5
        window: 30s
    ports:
      - "8000:80"
    
    # Uncomment in order to inject a model dir
    # volumes:
    ###   - /path/to/models:/models
