version: "3.9"

services:

  app:
    build: ../
    env_file: .env
    deploy:
      restart_policy:
        max_attempts: 5
        window: 30s
    ports:
      - "8000:80"
    volumes:
      - './models/PhosphopediaModels/production:/models'
